### PR TITLE
Add support for Nether and End dimensions

### PR DESCRIPTION
**Pull request by barrett777**
Add support for Nether and End dimensions

I also added '40' to list of chunk versions supported.  I don't know what changed though.

I do get some errors about some block NBT not being able to load, but it's for a very small number of blocks

### CODE REVIEW

**Comment by barrett777** [comment]
Nevermind, I removed chunk version '40' being supported.  My use case is read only, so I don't care if a chunk version isn't fully supported.  I realize now though that others may have data loss trying to save changes if a chunk version isn't fully supported

**Review by BluCodeGH — CHANGES_REQUESTED** [review]
This looks good overall, but in order to not modify the API and keep it simple for common use-cases (overworld only) I think we should make `dimension` an optional keyword argument at the end of the relevant functions.

In terms of the chunk version, I've never been able to really figure out what changes between them. If you want to try to set some blocks in a chunk with version 40 to verify that it doesn't explicitly break I'm good with marking it as supported.

IIRC the NBT errors occur when a block with NBT was removed but the game didn't clean up the actual NBT data for some reason or other, I wouldn't worry about it.

**Comment by barrett777** [comment]
Ok I made `dimension` optional.  I didn't add version 40 though, too much responsibility :) Also I see the open issue #14 so there may be more versions < 40, and I don't want to dig into that

**Review by BluCodeGH — APPROVED** [review]
Fair enough, thanks for your help!

**Pull request merged**
